<a href="https://colab.research.google.com/github/AhmadBinAbdulJabbar/campusx/blob/main/session_15_numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([20, 83, 21, 53, 79, 86, 38, 95, 12, 21, 77, 48, 54, 18, 51])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[25, 66, 71, 96],
       [99, 72, 24, 85],
       [89, 36, 86, 59],
       [79, 85, 85, 19],
       [92, 75, 83, 46],
       [46, 47, 86, 61]])

In [3]:
np.sort(a)[::-1]

array([95, 86, 83, 79, 77, 54, 53, 51, 48, 38, 21, 21, 20, 18, 12])

In [4]:
np.sort(b,axis=0)

array([[25, 36, 24, 19],
       [46, 47, 71, 46],
       [79, 66, 83, 59],
       [89, 72, 85, 61],
       [92, 75, 86, 85],
       [99, 85, 86, 96]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [5]:
# code
np.append(a,200)

array([ 20,  83,  21,  53,  79,  86,  38,  95,  12,  21,  77,  48,  54,
        18,  51, 200])

In [6]:
b

array([[25, 66, 71, 96],
       [99, 72, 24, 85],
       [89, 36, 86, 59],
       [79, 85, 85, 19],
       [92, 75, 83, 46],
       [46, 47, 86, 61]])

In [7]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[2.50000000e+01, 6.60000000e+01, 7.10000000e+01, 9.60000000e+01,
        4.55008543e-01],
       [9.90000000e+01, 7.20000000e+01, 2.40000000e+01, 8.50000000e+01,
        7.16678555e-01],
       [8.90000000e+01, 3.60000000e+01, 8.60000000e+01, 5.90000000e+01,
        3.50155770e-01],
       [7.90000000e+01, 8.50000000e+01, 8.50000000e+01, 1.90000000e+01,
        4.24401574e-01],
       [9.20000000e+01, 7.50000000e+01, 8.30000000e+01, 4.60000000e+01,
        4.81324291e-02],
       [4.60000000e+01, 4.70000000e+01, 8.60000000e+01, 6.10000000e+01,
        3.71103155e-01]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [8]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [12]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [13]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [15]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [16]:
# code
a.shape

(15,)

In [17]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [18]:
np.expand_dims(a,axis=1)

array([[20],
       [83],
       [21],
       [53],
       [79],
       [86],
       [38],
       [95],
       [12],
       [21],
       [77],
       [48],
       [54],
       [18],
       [51]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [20]:
a

array([20, 83, 21, 53, 79, 86, 38, 95, 12, 21, 77, 48, 54, 18, 51])

In [19]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  3,  4,  5,  7, 10, 12, 14]),)

In [21]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([20,  0, 21,  0,  0,  0, 38,  0, 12, 21,  0, 48,  0, 18,  0])

In [22]:
np.where(a%2 == 0,0,a)

array([ 0, 83, 21, 53, 79,  0,  0, 95,  0, 21, 77,  0,  0,  0, 51])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [23]:
# code
a

array([20, 83, 21, 53, 79, 86, 38, 95, 12, 21, 77, 48, 54, 18, 51])

In [24]:
np.argmax(a)

np.int64(7)

In [25]:
b

array([[25, 66, 71, 96],
       [99, 72, 24, 85],
       [89, 36, 86, 59],
       [79, 85, 85, 19],
       [92, 75, 83, 46],
       [46, 47, 86, 61]])

In [26]:
np.argmax(b,axis=0)

array([1, 3, 2, 0])

In [27]:
np.argmax(b,axis=1)

array([3, 0, 0, 1, 0, 2])

In [28]:
# np.argmin
np.argmin(a)

np.int64(8)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [29]:
a

array([20, 83, 21, 53, 79, 86, 38, 95, 12, 21, 77, 48, 54, 18, 51])

In [30]:
np.cumsum(a)

array([ 20, 103, 124, 177, 256, 342, 380, 475, 487, 508, 585, 633, 687,
       705, 756])

In [31]:
b

array([[25, 66, 71, 96],
       [99, 72, 24, 85],
       [89, 36, 86, 59],
       [79, 85, 85, 19],
       [92, 75, 83, 46],
       [46, 47, 86, 61]])

In [33]:
np.cumsum(b,axis=1)

array([[ 25,  66,  71,  96],
       [124, 138,  95, 181],
       [213, 174, 181, 240],
       [292, 259, 266, 259],
       [384, 334, 349, 305],
       [430, 381, 435, 366]])

In [34]:
np.cumsum(b)

array([  25,   91,  162,  258,  357,  429,  453,  538,  627,  663,  749,
        808,  887,  972, 1057, 1076, 1168, 1243, 1326, 1372, 1418, 1465,
       1551, 1612])

In [37]:
a
b

array([[25, 66, 71, 96],
       [99, 72, 24, 85],
       [89, 36, 86, 59],
       [79, 85, 85, 19],
       [92, 75, 83, 46],
       [46, 47, 86, 61]])

In [35]:
# np.cumprod
np.cumprod(a)

array([                  20,                 1660,                34860,
                    1847580,            145958820,          12552458520,
               476993423760,       45314375257200,      543772503086400,
          11419222564814400,   879280137490708800,  5311958452134919168,
       -8302148764067190784, -1864725163533021184, -2867262971636322304])

In [40]:
np.cumprod(b, axis=1)

array([[      25,     1650,   117150, 11246400],
       [      99,     7128,   171072, 14541120],
       [      89,     3204,   275544, 16257096],
       [      79,     6715,   570775, 10844725],
       [      92,     6900,   572700, 26344200],
       [      46,     2162,   185932, 11341852]])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [41]:
a

array([20, 83, 21, 53, 79, 86, 38, 95, 12, 21, 77, 48, 54, 18, 51])

In [45]:
np.percentile(a,50)

np.float64(51.0)

In [46]:
np.median(a)

np.float64(51.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [47]:
# code
a

array([20, 83, 21, 53, 79, 86, 38, 95, 12, 21, 77, 48, 54, 18, 51])

In [49]:
np.histogram(a,bins=[0, 10 ,50,100])

(array([0, 7, 8]), array([  0,  10,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [53]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,2,5])

np.corrcoef(salary,experience)

array([[1.        , 0.97388583],
       [0.97388583, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [54]:
# code
a


array([20, 83, 21, 53, 79, 86, 38, 95, 12, 21, 77, 48, 54, 18, 51])

In [59]:
items = [10,20,38,40,50,60,70,80,90,100]
# np.isin(a,items)
a[np.isin(a,items)] # using it as mask

array([20, 38])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [60]:
# code
a

array([20, 83, 21, 53, 79, 86, 38, 95, 12, 21, 77, 48, 54, 18, 51])

In [61]:
np.flip(a)

array([51, 18, 54, 48, 77, 21, 12, 95, 38, 86, 79, 53, 21, 83, 20])

In [62]:
b

array([[25, 66, 71, 96],
       [99, 72, 24, 85],
       [89, 36, 86, 59],
       [79, 85, 85, 19],
       [92, 75, 83, 46],
       [46, 47, 86, 61]])

In [64]:
np.flip(b) # both row and col flip

array([[61, 86, 47, 46],
       [46, 83, 75, 92],
       [19, 85, 85, 79],
       [59, 86, 36, 89],
       [85, 24, 72, 99],
       [96, 71, 66, 25]])

In [67]:
np.flip(b,axis=1) # row wise flip
np.flip(b, axis = 0) # col wise flip

array([[46, 47, 86, 61],
       [92, 75, 83, 46],
       [79, 85, 85, 19],
       [89, 36, 86, 59],
       [99, 72, 24, 85],
       [25, 66, 71, 96]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [70]:
# code
a

array([110, 530,  21,  53,  79,  86,  38,  95,  12,  21,  77,  48,  54,
        18,  51])

In [69]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [73]:
# code
a

array([110, 530,  21,  53,  79,  86,  38,  95,  12,  21,  77,  48,  54,
        18,  51])

In [72]:
np.delete(a,[0,2,4])

array([530,  53,  86,  38,  95,  12,  21,  77,  48,  54,  18,  51])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [74]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [75]:
np.intersect1d(m,n)

array([3, 4, 5])

In [76]:
np.setdiff1d(n,m)

array([6, 7])

In [77]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [81]:
m[np.isin(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [82]:
# code
a

array([110, 530,  21,  53,  79,  86,  38,  95,  12,  21,  77,  48,  54,
        18,  51])

In [83]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 25, 53, 75, 75, 38, 75, 25, 25, 75, 48, 54, 25, 51])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals