<a href="https://colab.research.google.com/github/AhmadBinAbdulJabbar/campusx/blob/main/task_15_numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [6]:
# code here
import numpy as np

matrix = np.random.randint(0, 100, (4, 3))
print("Original matrix:")
print(matrix)

Original matrix:
[[43 12 21]
 [76 91 38]
 [35 44 10]
 [70 54  5]]


In [14]:
np.sort(matrix)
np.argsort(matrix[:, 1])
np.argsort(matrix.max(axis=1))
np.sort(matrix, axis=None).reshape(4,3)

array([[ 5, 10, 12],
       [21, 35, 38],
       [43, 44, 54],
       [70, 76, 91]])

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [25]:
# code here
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
# Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]

# i. Add marks every student of an extra subject in the same array.
# The extra_subject needs to be reshaped to a column vector (5, 1) to be concatenated column-wise.
marks_with_extra_subject = np.concatenate((marks, np.array(extra_subject).reshape(-1, 1)), axis=1)
print("Marks with extra subject:")
print(marks_with_extra_subject)

# ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
marks_with_2_students_add = np.concatenate((marks_with_extra_subject, np.array([rec1, rec2])), axis=0)
print("Marks with extra students:")
print(marks_with_2_students_add)

# iii. Add extra column with sum of all subjects(5-subjects) marks
total_marks = np.sum(marks_with_2_students_add, axis=1, keepdims=True)
marks_with_total_marks = np.concatenate((marks_with_2_students_add, total_marks), axis=1)
print("Marks with total marks:")
print(marks_with_total_marks)


# iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.
sorted_marks = marks_with_total_marks[np.argsort(marks_with_total_marks[:, -1])]
top_2_rows = sorted_marks[-2:]
print("Top 2 rows:")
print(top_2_rows)

Marks with extra subject:
[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]
Marks with extra students:
[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [77 83 98 95 89]
 [92 71 52 61 53]]
Marks with total marks:
[[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]
Top 2 rows:
[[ 92  71  52  61  53 329]
 [ 77  83  98  95  89 442]]


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [30]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

print("Column wise: ")
print(np.unique(arr, axis=1))
print("Row wise: ")
print(np.unique(arr, axis=0))


Column wise: 
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
Row wise: 
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [31]:
# code here
arr = np.arange(12).reshape(3,4)
print(arr)
print(np.flip(arr))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [35]:
# code here
arr = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])

x = 6
print(np.where(np.any(arr > x, axis=1)))

TypeError: where() got an unexpected keyword argument 'axis'

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [39]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [45]:
# code here
np.concatenate((arr1, arr2, arr3))


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [49]:
# code here
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))

print(arr)
print(np.min(arr))
print(np.max(arr))
arr = np.delete(arr, np.argmax(arr))
arr = np.delete(arr, np.argmin(arr))
print(arr)

[[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
  181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
  353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
  921 490 527 972 278 307 840 958 246 449 251 957 103 627 920 824 356 825
  173 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211
  771 270 308 231 952 514 699 702 433 900 373 318 998 265 503 320 230 324
  922 967 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930
  325 729 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528
  395 525 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859
  618 226 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748
  291 194 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207
  883 588]]
103
998
[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
 181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
 353 975 592 997 137

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [53]:
# code here
a = np.arange(100, 701, 100)
a = np.clip(a, 100, 200)
print(a)
a.sort()
print(np.cumsum(a))

[100 200 200 200 200 200 200]
[ 100  300  500  700  900 1100 1300]


### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [55]:
# code here
arr = np.random.random(10)
arr = np.round(arr, 3)
print(arr)
print(np.percentile(arr, 0))
print(np.percentile(arr, 100))
print(np.percentile(arr, 51) - np.percentile(arr, 50))

[0.158 0.947 0.437 0.355 0.661 0.704 0.156 0.793 0.905 0.955]
0.156
0.955
0.00387000000000004
