<a href="https://colab.research.google.com/github/AhmadBinAbdulJabbar/campusx/blob/main/Task_13_NumPy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [ ]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
#Code here
# a1 = np.zeros(10,dtype=int)
# a1[4] = 1
# a1

a1 = np.empty(10) * np.nan
a1[4] = 1
a1

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
#Code here
a = input("Enter a number")
a = int(a)
b = input("Enter a number")
b = int(b)
a3 = np.random.random((a,b))
print(a3)
print(np.mean(a3))

Enter a number2
Enter a number3
[[0.23049261 0.52801136 0.45292768]
 [0.0122452  0.99732853 0.87210265]]
0.5155180058714076


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [3]:
#Code here
import numpy as np
def border_ones(dimensions):
  arr = np.ones(dimensions, dtype=int)

  arr[1:-1,1:-1] = 0
  print(arr)

border_ones((4,4))

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [7]:
#Code here
np.linspace(0,1,12)[1:-1]


array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [8]:
#Code here
# np.eye(3,4)
# no

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [13]:
#Code here
# np.full((5,5),np.arange(5))
# np.tile(np.arange(5),(5,1))
np.random.randint(0,4, size=25).reshape(5,5)

array([[1, 2, 2, 2, 2],
       [2, 3, 2, 3, 2],
       [2, 1, 0, 3, 1],
       [3, 0, 1, 0, 0],
       [2, 1, 2, 1, 1]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [18]:
#code here
points = np.random.randint(1,200, size=20).reshape(10,2)
# print(coordinates)
given_point = np.array([2,3])

distances = np.sqrt(np.sum((points - given_point)**2, axis=1)).astype(int)
print(distances)

[165 132 115  43 268 202  93 153 176 114]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [29]:
#Code here
a = np.arange(1, (6*7*8)+1).reshape(6,7,8)
a
print(np.where(a == 100))
for i in np.nditer(a):
  if i == 100:
    print(np.where(a == i))

(np.int64(1), np.int64(5), np.int64(4))
(array([1]), array([5]), array([3]))
(array([1]), array([5]), array([3]))


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [33]:
#Code here
# inp = "1 2 3 4 -8 -10"
# inp_split = inp.split()
# a = np.array(inp_split, dtype=float)[::-1]
# print(a)


#Code here
a=np.array([int(i) for i in input().split()][::-1],dtype=np.float32)
a

1 2


array([2., 1.], dtype=float32)

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [35]:
#Code here
def count_number_elements(a):
  return a.size

count_number_elements(np.array([1, 2]))
count_number_elements(np.array([]))

0

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [38]:
#Code here
def softmax(arr):
  if type(arr) != np.ndarray:
    raise TypeError("Requires Numpy Array")
  if arr.ndim > 1:
    raise TypeError("Requires 1D Array")

  exp_values = np.exp(arr)
  return exp_values / np.sum(exp_values)

  # shifted = x - np.max(x)
  # exp_values = np.exp(shifted)
  # return exp_values / np.sum(exp_values)
  # return np.exp(arr) / np.sum(np.exp(arr), axis=0)


print(softmax(np.array([86.03331084, 37.7285648, 48.64908087, 87.16563062, 38.40852563, 37.20006318])))

print(softmax(np.array([33.17344305, 45.61961654, 82.05405781, 80.9647098, 68.82830233, 91.52064278])))

[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]
[4.57181033e-26 1.16249922e-20 7.73872594e-05 2.60358426e-05
 1.39571531e-10 9.99896577e-01]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [42]:
#Coder here
def infinite_vstack(*args):
  for i in args:
    if type(i) != np.ndarray:
      raise TypeError("Requires Numpy Array")
  return np.vstack(args)

a= np.array([[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9]])

b= np.array([[1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1]])

print(infinite_vstack(a,b))

a = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9]])

b = np.array([[1, 1, 1, 1, 1],
              [1, 1, 1, 1, 1]])

c = np.array([[0.10117373, 0.1677244,  0.73764059, 0.83166097, 0.48985695],
              [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

print(infinite_vstack(a,b,c))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [47]:
#Code here
def date_array(start, end):
  if type(start) != str or type(end) != str:
    raise TypeError("Requires String")

  return np.arange(start, end, dtype='datetime64[D]')

print(date_array(start = '2020-09-15', end = '2020-09-25'))
print()
print(date_array(start = '2022-12-01', end = '2022-12-06'))
print()
print(date_array(start = '2020-11-25', end = '2020-11-30'))

['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24']

['2022-12-01' '2022-12-02' '2022-12-03' '2022-12-04' '2022-12-05']

['2020-11-25' '2020-11-26' '2020-11-27' '2020-11-28' '2020-11-29']


###`Q-14:` Subtract the mean of each row from a matrix.

In [51]:
#code here
def mean_row(matrix):
  return matrix - matrix.mean(axis=1, keepdims=True)

mean_row(np.array([[1,2,3],[4,5,6],[7,8,9]]))

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [52]:
#Code here
def swap_columns(arr):
  arr[:, [0, 1]] = arr[:, [1, 0]]
  return arr

swap_columns(np.array([[1,2,3],[4,5,6],[7,8,9]]))

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

###`Q-16:` Replace odd elements in arrays with -1.

In [63]:
#Code here
arr = np.random.randint(1, 100, size=6).reshape(2,3)
# ab = arr.ravel()
# print(arr)
# for i in range(len(ab)):
#   if i % 2 != 0:
#     ab[i] = -1

# print(ab.reshape(2,3))

# 1st method using where
# result = np.where(a % 2 != 0, -1, a)
# result

# 2 method using mask
arr[arr % 2 != 0] = -1
arr

array([[60, 62, -1],
       [-1, -1, 86]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
#Code here

In [65]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

# result = np.where(a > b, a, b)
# print(result)

result = np.maximum(a,b)
print(result)

[6 3 1 7 8]
[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [67]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

arr1_norm = (arr1 - arr1.min()) / (arr1.max() - arr1.min())
arr1_norm

array([[0.33838487, 0.64686737, 0.58441823, 0.36727014, 0.11940602],
       [0.24115134, 0.68999186, 0.15286819, 0.41619203, 0.57272172],
       [0.21928397, 0.02186737, 0.43917819, 0.36849064, 0.67748169],
       [1.        , 0.63618796, 0.91832791, 0.14585028, 0.50081367],
       [0.36940602, 0.01057771, 0.12988202, 0.65246135, 0.63944264],
       [0.59143613, 0.11594793, 0.47945484, 0.82190806, 0.04576892],
       [0.97477624, 0.24633849, 0.76393409, 0.02796989, 0.67931245],
       [0.09143613, 0.5081367 , 0.        , 0.57973963, 0.51271359]])

In [ ]:
#Code here

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [71]:
#Code here
def rank_fun(arr, n):
  if n > len(arr):
    raise ValueError("n should be less than or equal to the length of the array")
  arr = np.sort(arr)
  return arr[-n]

print(rank_fun(np.array([12,34,40,7,1,0]), 3))
print(rank_fun(np.array([12,34,40,7,1,0]), 1))


[ 0  1  7 12 34 40]
12
[ 0  1  7 12 34 40]
40


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [77]:
#code here

def pattern(arr):
  result = np.concatenate((np.repeat(arr, 3), np.tile(arr, 3)), axis=0)
  return result
pattern(np.array([1,2,3]))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])